Update master_abc-summer.yml

diff --git a/.github/workflows/master_abc-summer.yml b/.github/workflows/master_abc-summer.yml
--- a/.github/workflows/master_abc-summer.yml
+++ b/.github/workflows/master_abc-summer.yml
@@ -6,7 +6,9 @@ on:
   push:
     branches:
       - master
-  workflow_dispatch:
+  pull_request:
+    branches:
+      - master
 
 jobs:
   test:
@@ -20,26 +22,25 @@ jobs:
         uses: actions/setup-node@v3
         with:
           node-version: '18.x'
-
-
+          
       - name: Create .env file
         run: |
           echo "CONNECTION_STRING=${CONNECTION_STRING}" > .env
 
-      - name: Display .env content
-        run: cat .env
-        
-          
-      - name: View directory
-        run: | 
-          ls
-
-
-      - name: npm install, build, and test
+      - name: Run tests
         run: |
           npm install
           npm run test --if-present
-  
+
+      - name: Check test status
+        run: |
+          if ! npm test; then
+            echo "Tests failed, preventing merge"
+            exit 1
+          else
+            echo "Tests passed, ready to merge"
+          fi
+    
   build:
     runs-on: 'ubuntu-latest'
     needs: test
